Activity/urls.py
from django.urls import re_path

from . import views

#name space des urls de l'application
app_name='activities'

urlpatterns = [
    re_path(r'^$', views.index, name='index'),
]

maia/urls.py
from django.contrib import admin
#from django.conf.urls import include
from django.urls import re_path, include

from . import views

urlpatterns = [
    re_path(r'^$', views.home, name = 'home'),
    re_path(r'^Activity/', include('Activity.urls')),
    re_path(r'^admin/', admin.site.urls),
]

Activity/models.py
from django.db import models

# Create your models here.

Activity/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
	mypost=['Act1', 'Act2', 'Act3']
	return render(request,'Activity/index', {'posts': mypost})

maia/views.py
from django.shortcuts import render

def home(request):
	return render(request,'home.html')

Activity/templates/Activity/index.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
	"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">

<head>
	<title>Activities</title>
	<meta http-equiv="content-type" content="text/html;charset=utf-8" />
	<meta name="generator" content="Geany 1.33" />
</head>

<body>
	<h1>Service Activities<h1>
	<h2>Métadonnées</h2>
		<h3>Nombre d'activités : {{posts|length}}</h3>
	<h2>Liste</h2>
	<ul>
		{% for act in posts	%}
		<li> {{act}}</li>
		{% endfor %}
	</ul>
</body>

</html>

templates/home.html
<!DOCTYPE html>
<head>
	<title>Maia Project</title>
	<meta http-equiv="content-type" content="text/html;charset=utf-8" />
</head>

<body>
	<h1>Home<h1>
	<p><a href="{% url 'activities:index' %}">ici</a></p>
</body>

</html>